export const options: any = [
    'Sr. No.',
    'Generating Station (Cleaned)',
    'Generating Station (Reported)',
    'Type',
    'Source',
    'MYT -Mus',
    'Actual -Mus',
    'MYT - Rs. Crs',
    '- Rs. Crs',
    'Per Unit Rate',
    'Date',
    'PPA = Charge',
    'PPA - Variable Charge',
    'PPA - Total Charge',
    'PPA (Y/N)',
    'Utilization',
    'Comment',
    'Capacity Allocated',
    'PPA Utilisation',
    'Total Capacity',
    'Total Capacity',
    'Availability',
    'Availability',
    'PLF',
    'PLF',
    'Gross Generation',
    'Gross Generation',
    'Auxiliary Consumption excluding FGD',
    'Auxiliary Consumption excluding FGD',
    'Auxiliary Consumption for FGD',
    'Auxiliary Consumption for FGD',
    'Total Auxiliary Consumption',
    'Total Auxiliary Consumption',
    'Total Auxiliary Consumption (= 1.6 + 1.8)',
    'Total Auxiliary Consumption (= 1.6 + 1.8)',
    'Net Generation (= 1.4 - 1.10)',
    'Net Generation (= 1.4 - 1.10)',
    'Heat Rate',
    'Heat Rate',
    'Secondary Fuel Oil Consumption',
    'Secondary Fuel Oil Consumption',
    'Transit Loss for Domestic and Washed Coal',
    'Transit Loss for Domestic and Washed Coal',
    'Transit Loss for Imported Coal',
    'Transit Loss for Imported Coal',
    'nan',
    'nan',
    'SHR coal component',
    'SHR coal component',
    'Fuel Parameters (For each Primary and Secondary Fuel)',
    'Fuel Parameters (For each Primary and Secondary Fuel)',
    'Calorific Value',
    'Calorific Value',
    'Domestic Coal (As Billed)',
    'Domestic Coal (As Billed)',
    'Imported Coal (As Billed)',
    'Imported Coal (As Billed)',
    'Wash Coal (As Billed)',
    'Wash Coal (As Billed)',
    'Domestic Coal (As Received)-',
    'Domestic Coal (As Received)-',
    'GCV loss between loading end and unloading end-- Domestic',
    'GCV loss between loading end and unloading end-- Domestic',
    'GCV loss between loading end and unloading end as per directions in MERC Order in Case No. 180 0f 202020 (Min. of or 625)',
    'GCV loss between loading end and unloading end as per directions in MERC Order in Case No. 180 0f 202020 (Min. of or 625)',
    'Domestic coal As received GCV for FAC computation',
    'Domestic coal As received GCV for FAC computation',
    'Wash Coal (As Received)',
    'Wash Coal (As Received)',
    'GCV loss between loading end and unloading end-- Wash Coal',
    'GCV loss between loading end and unloading end-- Wash Coal',
    'GCV loss between loading end and unloading end for Wash Coal as per Case No. 296 0f 2019 (Min. of or 300)',
    'GCV loss between loading end and unloading end for Wash Coal as per Case No. 296 0f 2019 (Min. of or 300)',
    'Wash coal As received GCV for FAC computation',
    'Wash coal As received GCV for FAC computation',
    'Imported Coal (As Received)',
    'Imported Coal (As Received)',
    'Weighted Avg Raw,Wash & Imported Coal for FAC Computations',
    'Weighted Avg Raw,Wash & Imported Coal for FAC Computations',
    'Weighted avg. received GCV -',
    'Weighted avg. received GCV -',
    'L.D.O',
    'L.D.O',
    'F.O',
    'F.O',
    'Fuel 4',
    'Fuel 4',
    'Calorific Value after stacking loss',
    'Calorific Value after stacking loss',
    'Domestic Coal (As Fired)--',
    'Domestic Coal (As Fired)--',
    'Stacking Loss',
    'Stacking Loss',
    'Stacking Loss Approved',
    'Stacking Loss Approved',
    'Stacking Loss',
    'Stacking Loss',
    'stacking loss to be considered as per MERC Regulations',
    'stacking loss to be considered as per MERC Regulations',
    'Coal (As Fired)- to be considered for energy charge computation',
    'Coal (As Fired)- to be considered for energy charge computation',
    'Landed Fuel Price per unit',
    'Landed Fuel Price per unit',
    'Domestic Coal',
    'Domestic Coal',
    'Imported Coal',
    'Imported Coal',
    'Wash Coal',
    'Wash Coal',
    'Weighted AVG price',
    'Weighted AVG price',
    'Wtd. Avg. Oil price',
    'Wtd. Avg. Oil price',
    'Fuel Consumption and Heat Contribution (for each fuel separately)',
    'Fuel Consumption and Heat Contribution (for each fuel separately)',
    'Specific Fuel Consumption',
    'Specific Fuel Consumption',
    'Total Fuel Consumption',
    'Total Fuel Consumption',
    'Heat content',
    'Heat content',
    'Total Heat content',
    'Total Heat content',
    'Total Fuel Cost',
    'Total Fuel Cost',
    'Other Charges and Adjustments',
    'Other Charges and Adjustments',
    'Other Charges (Pl. specify details)',
    'Other Charges (Pl. specify details)',
    'Other Adjustments (Pl. specify details)',
    'Other Adjustments (Pl. specify details)',
    'Total Other Charges and Adjustments',
    'Total Other Charges and Adjustments',
    'Total Cost (= 4 + 5)',
    'Total Cost (= 4 + 5)',
    'Cost of Generation (at Generation Terminal) (',
    'Cost of Generation (at Generation Terminal) (',
    'Energy Charge (= 6/1.11)',
    'Energy Charge (= 6/1.11)',
    'Operational parameters',
    'Operational parameters',
    'FIXED CHARGE'
  ];
  